spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5433/ebank
    username: emin
    password: 1111
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true